version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
    expose:
      - 5672

  api:
    build: ./backend/api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api:/api/
    restart: always
    depends_on:
      - rabbitmq

  user_service:
    build: ./backend/user_service
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./backend/user_service:/app/
    ports:
      - '8001:8001'
    depends_on:
      - user_db
      - rabbitmq

  user_db:
    image: postgres
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - backend/user_service/.env


volumes:
  postgres_data_user:

#  service1:
#    container_name: template_service1
#    build: ./backend/service1
#    volumes:
#      - ./backend/service1:/service1/
#    restart: always
#
#  service2:
#    container_name: template_service2
#    build: ./backend/service2
#    volumes:
#      - ./backend/service2:/service2/
#    restart: always
